kiwi: Enable sndmonitor for audio.
Monitor sound card status and report online/offline
events back to the streams registered with it and to audio_dev.

This flag is also needed to avoid compilation errors within
the hardware/qcom/audio hal.

hardware/qcom/audio-caf/msm8952/hal/audio_hw.c:2005:13: error: unused function 'out_snd_mon_cb' [-Werror,-Wunused-function]
static void out_snd_mon_cb(void * stream, struct str_parms * parms)
            ^
hardware/qcom/audio-caf/msm8952/hal/audio_hw.c:2773:13: error: unused function 'in_snd_mon_cb' [-Werror,-Wunused-function]
static void in_snd_mon_cb(void * stream, struct str_parms * parms)
            ^
hardware/qcom/audio-caf/msm8952/hal/audio_hw.c:3952:13: error: unused function 'adev_snd_mon_cb' [-Werror,-Wunused-function]
static void adev_snd_mon_cb(void *cookie, struct str_parms *parms)

Change-Id: If9d1ac020f035ca16a04b76665e30b62da0fab25